# Generated by Django 6.1 on 2026-09-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
                ('descripcion', models.CharField()),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'actividades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AplicacionMedicamento',
            fields=[
                ('id_aplicacion', models.AutoField(primary_key=True, serialize=False)),
                ('id_medicamento_medicamento', models.IntegerField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('dosis_administrada', models.CharField()),
                ('via_administracion', models.CharField()),
                ('estado', models.BooleanField()),
                ('observacion', models.CharField()),
            ],
            options={
                'db_table': 'aplicacion_medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AplicacionMedicamentos',
            fields=[
                ('id_aplicacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField()),
                ('hora', models.CharField()),
                ('estado', models.CharField()),
                ('observaciones', models.CharField()),
            ],
            options={
                'db_table': 'aplicacion_medicamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsignacionPacienteCuidador',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField()),
                ('observaciones', models.CharField()),
            ],
            options={
                'db_table': 'asignacion_paciente_cuidador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsignacionTurnoUsuario',
            fields=[
                ('id_asignacion_turno_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField()),
            ],
            options={
                'db_table': 'asignacion_turno_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
                ('tipo_registro', models.CharField()),
                ('descripcion', models.CharField()),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'bitacora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleEntregaInsumos',
            fields=[
                ('id_detalle_entrega_insumos', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'db_table': 'detalle_entrega_insumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleEntregaMedicamento',
            fields=[
                ('id_detalle_entrega_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'db_table': 'detalle_entrega_medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosticos',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField()),
                ('estado', models.BooleanField()),
                ('fecha_diagnostico', models.DateTimeField()),
            ],
            options={
                'db_table': 'diagnosticos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('id_enfermedad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
                ('descripcion', models.CharField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'enfermedades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntregaInsumo',
            fields=[
                ('id_entrega_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('fehca_entrega', models.DateTimeField()),
                ('observaciones', models.CharField()),
            ],
            options={
                'db_table': 'entrega_insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntregaMedica',
            fields=[
                ('id_entrega_medica', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateTimeField()),
                ('observaciones', models.CharField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'entrega_medica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventosAdversos',
            fields=[
                ('id_evento_adverso', models.AutoField(primary_key=True, serialize=False)),
                ('id_evento', models.CharField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('descripcion', models.CharField()),
                ('acciones_realizadas', models.CharField()),
                ('estado', models.CharField()),
            ],
            options={
                'db_table': 'eventos_adversos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinicas',
            fields=[
                ('id_historia_clinica', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField()),
                ('antecedentes', models.CharField()),
                ('alergias', models.CharField()),
                ('observaciones', models.CharField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'historia_clinicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenesEventoAdverso',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.CharField()),
                ('descripcion', models.CharField()),
                ('fecha_subida', models.DateTimeField()),
            ],
            options={
                'db_table': 'imagenes_evento_adverso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
                ('descripcion', models.CharField()),
                ('unidad_medida', models.CharField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'insumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_actual', models.IntegerField()),
                ('cantidad_minima', models.IntegerField()),
                ('fecha_ultimo_ingreso', models.DateTimeField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id_medicamentos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
                ('vencimiento', models.DateField()),
                ('descripcion', models.CharField()),
                ('principio_activo', models.CharField()),
                ('concentracion', models.CharField()),
                ('presentacion', models.CharField()),
                ('estado', models.BooleanField()),
                ('unidad_medida', models.CharField()),
            ],
            options={
                'db_table': 'medicamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInsumo',
            fields=[
                ('id_movimiento_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_insumo', models.CharField()),
                ('cantidad', models.IntegerField()),
                ('fecha_movimiento', models.DateTimeField()),
                ('observacion', models.CharField()),
            ],
            options={
                'db_table': 'movimiento_insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoMedicamento',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_movimiento', models.DateTimeField()),
                ('observaciones', models.CharField()),
            ],
            options={
                'db_table': 'movimiento_medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
                ('apellido', models.CharField()),
                ('eps', models.CharField()),
                ('sede', models.CharField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('habitacion', models.IntegerField()),
                ('responsable', models.CharField()),
                ('tipo_documento', models.CharField()),
                ('numero_documento', models.CharField()),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField()),
                ('telefono', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pacientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permisos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
                ('descripcion', models.CharField()),
            ],
            options={
                'db_table': 'permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermisosRol',
            fields=[
                ('id_permisos_rol', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'permisos_rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
                ('descripcion', models.CharField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id_signos_vitales', models.AutoField(primary_key=True, serialize=False)),
                ('temperatura', models.CharField()),
                ('presion_sistolica', models.CharField()),
                ('presion_diastolica', models.CharField()),
                ('frecuencia_cardiaca', models.CharField()),
                ('frecuencia_respiratoria', models.CharField()),
                ('saturacion_oxigeno', models.CharField()),
                ('peso', models.CharField()),
                ('fecha_hora', models.DateTimeField()),
                ('observaciones', models.CharField()),
            ],
            options={
                'db_table': 'signos_vitales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEmergencia',
            fields=[
                ('id_tipo_emergencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
                ('descripcion', models.CharField()),
                ('nivel', models.CharField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'tipo_emergencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id_tipo_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
                ('descripcion', models.CharField()),
                ('estado', models.CharField()),
            ],
            options={
                'db_table': 'tipo_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id_tipo_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
                ('descripcion', models.CharField()),
                ('estado', models.CharField()),
            ],
            options={
                'db_table': 'tipo_insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TratamientoMedicamento',
            fields=[
                ('id_tratamiento_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('dosis', models.IntegerField()),
                ('frecuencia', models.CharField()),
                ('via_administracion', models.CharField()),
                ('duracion', models.CharField()),
                ('cantidad_prescrita', models.CharField()),
                ('observaciones', models.CharField()),
                ('estado', models.CharField()),
            ],
            options={
                'db_table': 'tratamiento_medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tratamientos',
            fields=[
                ('id_tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.TimeField()),
                ('fecha_fin', models.TimeField()),
                ('indicaciones', models.CharField()),
                ('estado', models.CharField()),
            ],
            options={
                'db_table': 'tratamientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('estado', models.BooleanField()),
                ('nombre', models.CharField()),
                ('descripcion', models.CharField()),
            ],
            options={
                'db_table': 'turnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('nombres', models.CharField()),
                ('apellidos', models.CharField()),
                ('correo', models.CharField()),
                ('contrasena', models.CharField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('estado', models.BooleanField()),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField()),
                ('numero_documento', models.CharField()),
                ('telefono', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
